### ISSUE TITLE
Cutter with number of words same as cutter settings.

### ISSUE THREAD

**Issue by digitaljohn** [tcorral/Cutter.js#3]
For example... If I ask cutter to cut at 32 words, but the content contains a paragraph tag with exactly 32 words, no content is displayed (Well... an empty p tag). I click the 'more' button and it all shows.

**Comment by tcorral** [comment]
Fixed in https://github.com/tcorral/Cutter.js/commit/e9b579d9512cc92f243c1beda8c5d4b2208f2bf8
