### ISSUE TITLE
"..." with Paragraph Elements

### ISSUE THREAD

**Issue by digitaljohn** [tcorral/Cutter.js#4]
When I have a chunk of content, e.g.

```
<p>Some Content Here.</p>
```

It outputs:

```
<p>Some Content</p>
...
```

This does not look right as the "..." is separated from the last word visually. Currently I disable the "..." functionality by commenting out line `505` of commit: e9b579d9512cc92f243c1beda8c5d4b2208f2bf8

`oElement.appendChild(doc.createTextNode("..."));`

**Comment by tcorral** [comment]
This file is only the copy of Cutter.js for examples. What's the question?

**Comment by digitaljohn** [comment]
As described above. The "..." is separated from the text flow...

![image](https://f.cloud.github.com/assets/1425921/1370900/f77e8a18-3a2c-11e3-8daf-1f124b273728.png)

It should really look like this:

![image](https://f.cloud.github.com/assets/1425921/1370908/36a7bb24-3a2d-11e3-93d2-e429347fc914.png)

**Comment by digitaljohn** [comment]
This could be a potential solution...

```
if (this.bNeedViewMore && !this.bNotViewMore) {
  if (oElement.lastChild.nodeName == "P" ) {
    oElement.lastChild.appendChild(doc.createTextNode("..."));
  } else {
    oElement.appendChild(doc.createTextNode("..."));
  }
  oElement.appendChild(doc.createElement("br"));
  oElement.appendChild(this.oViewMore);
  this.setBehaviour();
}
```

**Comment by tcorral** [comment]
Please, could you make a pull request to include the fix?

2013/10/21 John Richard Chipps-Harding notifications@github.com
